AWSTemplateFormatVersion: '2019-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API DynamoDB  - varios metodos

Resources:
  Productos:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        Envioxid:
          Type: Api
          Properties:
            Path: /envios/{idEnvio}
            Method: get
        EnviosPendientes:
          Type: Api
          Properties:
            Path: /envios/pendientes
            Method: get
        CrearEnvio:
          Type: Api
          Properties:
            Path: /envios
            Method: post
        NuevoMovimientoEnvio:
          Type: Api
          Properties:
            Path: /envios/{idEnvio}/movimiento
            Method: post
        EnvioEntregado:
          Type: Api
          Properties:
            Path: /envios/{idEnvio}/entregado
            Method: post



            
